## Note that because this file is expected to be consumed in a dev container
## so the files have absolute paths that are correct for the container.

## dev configuration in general
[config.dev]
## Load parigot code from shared object
ParigotLibPath="/workspaces/parigot/build/syscall.so"
ParigotLibSymbol="ParigotInitialize"
Timezone = "US/Eastern"
[config.dev.Timeout]
Startup = 100 # millis
Complete = 20 # millis

# nutsdb service
[config.dev.microservice.nutsdb]
WasmPath="/workspaces/parigot/build/nutsdb.p.wasm"
PluginPath="/workspaces/parigot/build/nutsdb.so"
PluginSymbol="ParigotInitialize"


# kv is just a program, not a service
[config.dev.microservice.kv]
WasmPath="/workspaces/parigot/example/kv/build/kv.p.wasm"
Arg=[]
Env=[]
# this is the crucial line for parigot. "this is just a client and should run to completion".
Main=true

