baseURL = 'http://parigot.github.io/'
languageCode = 'en-us'
title = 'Parigot'
theme = "ace-documentation-1.0.4"

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>"
url = "https://github.com/iansmih/parigot"
weight = 10

