baseURL = 'https://parigot.info/'
languageCode = 'en-us'
title = 'Parigot'
theme = "ace-documentation-1.0.4"
ignorefiles = ["document/*", "internal/*"]
[params]
disableSearch = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.shortcuts]]
name = "<i class='fab fa-github'>Source</i>"
url = "https://github.com/iansmith/parigot"
weight = 10

