//go:build wasip1 

// Code generated by protoc-gen-parigot. DO NOT EDIT.
// source: http/v1/http.proto

package http


import(
    "context" 

    // this set of imports is _unrelated_ to the particulars of what the .proto imported... those are above
    lib "github.com/iansmith/parigot/lib/go"  
    "github.com/iansmith/parigot/lib/go/future"  
    "github.com/iansmith/parigot/lib/go/client"  
    "github.com/iansmith/parigot/api/shared/id"
    syscall "github.com/iansmith/parigot/g/syscall/v1" 

    "google.golang.org/protobuf/proto"
    "google.golang.org/protobuf/types/known/anypb"



)  
//
// Http from http/v1/http.proto
//
//service interface
type Http interface {
    Get(ctx context.Context,in *GetRequest) *FutureGet   
    Ready(context.Context,id.ServiceId) *future.Base[bool]
}

type Client interface {
    Get(ctx context.Context,in *GetRequest) *FutureGet   
}

// Client difference from Http: Ready() 
type Client_ struct {
    *client.BaseService
}
// Check that Client_ is a Client.
var _ = Client(&Client_{})

//
// method: Http.Get 
//
type FutureGet struct {
    Method *future.Method[*GetResponse,HttpErr]
} 

// This is the same API for output needed or not because of the Completer interface.
// Note that the return value refers to the process of the setup/teardown, not the
// execution of the user level code.
func (f * FutureGet) CompleteMethod(ctx context.Context,a proto.Message, e int32) syscall.KernelErr{
    out:=&GetResponse{}
    if err:= a.(*anypb.Any).UnmarshalTo(out); err!=nil {
        return syscall.KernelErr_UnmarshalFailed
    }
    f.Method.CompleteMethod(ctx,out,HttpErr(e)) 
    return syscall.KernelErr_NoError

}
func (f *FutureGet)Success(sfn func (proto.Message)) {
    x:=func(m *GetResponse){
        sfn(m)
    }
    f.Method.Success(x)
} 

func (f *FutureGet)Failure(ffn func (int32)) {
    x:=func(err HttpErr) {
        ffn(int32(err))
    }
    f.Method.Failure(x) 
}
func NewFutureGet() *FutureGet {
    f:=&FutureGet{
        Method: future.NewMethod[*GetResponse,HttpErr](nil,nil),
    } 
    return f
}
func (i *Client_) Get(ctx context.Context, in *GetRequest) *FutureGet { 
    mid, ok := i.BaseService.MethodIdByName("Get")
    if !ok {
        f:=NewFutureGet()
        f.CompleteMethod(ctx,nil,1)/*dispatch error*/
    }
    cid,kerr:= i.BaseService.Dispatch(mid,in) 
    f:=NewFutureGet()
    if kerr!=syscall.KernelErr_NoError{
        f.CompleteMethod(ctx,nil, 1)/*dispatch error*/
        return f
     }
    lib.MatchCompleter(cid,f)
    return f
}  
