#make then make prepdeploybase is required to populate build
FROM alpine:3.18
RUN apk update
RUN apk add libc6-compat
RUN apk add gcompat
#RUN gcompat include libresolv.so.2
RUN mkdir -p /app/build
COPY build/* /app/build/
WORKDIR /app
ENTRYPOINT ["ash"]
