// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: syscall/v1/syscall.proto

package syscall

import (
	v1 "github.com/iansmith/parigot/g/protosupport/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KernelErr int32

const (
	KernelErr_NoError KernelErr = 0
	// LocateError is return when the kernel cannot find the requested
	// service, given by a package name and service name pair.
	KernelErr_LocateError KernelErr = 1
	// UnmarshalFailed is used to indicate that in unmarshaling
	// a request or result, the protobuf layer returned an error.
	KernelErr_UnmarshalFailed KernelErr = 2
	// IdDispatch means that a dispatch call failed due to an
	// MethodId or ServiceId was not found.
	KernelErr_IdDispatch KernelErr = 3
	// NamespaceExhausted is returned when the kernel can no
	// along accept additional packages, services, or methods.  This is used
	// primarily to thwart attempts at DOS attacks.
	KernelErr_NamespaceExhausted KernelErr = 4
	// NotFound means that a package, service, or method that was requested
	// could not be found.
	KernelErr_NotFound KernelErr = 5
	// DataTooLarge means that the size of some part of method call was bigger
	// than the buffer allocated to receive it.  This could be a problem either on
	// the call side or the return side.
	KernelErr_DataTooLarge KernelErr = 6
	// Marshal means that a marshal of a protobuf has failed.
	KernelErr_MarshalFailed KernelErr = 7
	// CallerUnavailable means that the kernel could not find the original caller
	// that requested the computation for which results have been provided.
	// It is most likely because the caller was killed, exited or timed out.
	KernelErr_CallerUnavailable KernelErr = 8
	// KernelServiceAlreadyClosedOrExported means that some process has already
	// reported the service in question as closed or has already expressed that it is
	// exporting (implementing this service).  This is very likely a case where there
	// are two servers that think they are or should be implementing the same service.
	KernelErr_ServiceAlreadyClosedOrExported KernelErr = 9
	// ServiceAlreadyRequired means that this same process has already
	// required the given service.
	KernelErr_ServiceAlreadyRequired KernelErr = 10
	// DependencyCycle means that no deterministic startup ordering
	// exists for the set of exports and requires in use.  In other words,
	// you must refactor your program so that you do not have a cyle to make
	// it come up cleanly.
	KernelErr_DependencyCycle KernelErr = 11
	// NetworkFailed means that we successfully connected to the nameserver, but failed
	// during the communication process itself.
	KernelErr_NetworkFailed KernelErr = 12
	// NetworkConnectionLost means that our internal connection to the remote nameserver
	// was either still working but has lost "sync" in the protocol or the connection has
	// become entirely broken.  The kernel will close the connection to remote nameserver
	// and reestablish it after this error.
	KernelErr_NetworkConnectionLost KernelErr = 13
	// DataTooSmall means that the kernel was speaking some protocol with a remote server,
	// such as a remote nameserver, and data read from the remote said was smaller than the protocol
	// dictated, e.g. it did not contain a checksum after a data block.
	KernelErr_DataTooSmall KernelErr = 14
	// ConnectionFailed means that the attempt to open a connection to a remote
	// service has failed to connect.
	KernelErr_KernelConnectionFailed KernelErr = 15
	// NSRetryFailed means that we tried twice to reach the nameserver with
	// the given request, but both times could not do so.
	KernelErr_NSRetryFailed KernelErr = 16
	// DecodeError indicates that an attempt to extract a protobuf object
	// from an encoded set of bytes has failed.  Typically, this means that
	// the encoder was not called.
	KernelErr_DecodeError KernelErr = 17
	// ExecError means that we received a response from the implenter of a particular
	// service's function and the execution of that function failed.
	KernelErr_ExecError KernelErr = 18
	// DependencyFailure means that the dependency infrastructure has failed.  This is different
	// than when a user creates bad set of depedencies (KernelDependencyCycle). This
	// an internal to the kernel error.
	KernelErr_KernelDependencyFailure KernelErr = 19
	// AbortRequest indicates that the program that receives this error
	// should exit because the nameserver has asked it to do so.  This
	// means that some _other_ program has failed to start correctly, so this
	// deployment cannot succeed.
	KernelErr_AbortRequest KernelErr = 20
	// ExitRequested indicates that the program that receives this error
	// should exit because the nameserver permitted it to do so.  This is not really
	// an "error" but rather an indication that the caller who requested the
	// exit may do so immediately.
	KernelErr_ExitRequested KernelErr = 21
	// EncodeError indicates that an attempt encode a protobuf
	// with header and CRC has failed.
	KernelErr_EncodeError KernelErr = 22
	// ClosedErr indicates that that object is now closed.  This is used
	// as a signal when writing data between the guest and host.
	KernelErr_ClosedErr KernelErr = 23
	// GuestReadFailed indicates that we did not successfully read
	// from guest memory. This is usually caused by the proposed address
	// to read from being out of bounds.
	KernelErr_GuestReadFailed KernelErr = 24
	// GuestWriteFailed indicates that we did not successfully write
	// to guest memory. This is usually caused by the proposed address
	// for writing to being out of bounds.
	KernelErr_GuestWriteFailed KernelErr = 25
	// BadId indicates that you passed the zero value or the empty value of a
	// an id type into a system call.  This usually means that you did not
	// properly initialize a protobuf.
	KernelErr_BadId KernelErr = 26
	// NotReady that the service that was trying
	// to start was aborted because it returned false from Ready().
	// Usually this error indicates that the program has no way to
	// continue running.
	KernelErr_NotReady KernelErr = 27
	// NotRequired that a service has tried to Locate() another service
	// that that the first service did not Require() previously.
	KernelErr_NotRequired KernelErr = 28
	// RunTimeout means that the programs timeout has expired when waiting
	// for all the required dependencies to be fulfilled.
	KernelErr_RunTimeout KernelErr = 29
	// ReadOneTimeout means that the program was trying to request
	// a service/method pair to invoke, but the request timed out.
	KernelErr_ReadOneTimeout KernelErr = 30
	// BadCallId is returned when trying to match up the results
	// and the call of a function resulting in a promise. It is returned
	// if either there is no such cid registered yet or the cid
	// is already in use.
	KernelErr_BadCallId KernelErr = 31
)

// Enum value maps for KernelErr.
var (
	KernelErr_name = map[int32]string{
		0:  "NoError",
		1:  "LocateError",
		2:  "UnmarshalFailed",
		3:  "IdDispatch",
		4:  "NamespaceExhausted",
		5:  "NotFound",
		6:  "DataTooLarge",
		7:  "MarshalFailed",
		8:  "CallerUnavailable",
		9:  "ServiceAlreadyClosedOrExported",
		10: "ServiceAlreadyRequired",
		11: "DependencyCycle",
		12: "NetworkFailed",
		13: "NetworkConnectionLost",
		14: "DataTooSmall",
		15: "KernelConnectionFailed",
		16: "NSRetryFailed",
		17: "DecodeError",
		18: "ExecError",
		19: "KernelDependencyFailure",
		20: "AbortRequest",
		21: "ExitRequested",
		22: "EncodeError",
		23: "ClosedErr",
		24: "GuestReadFailed",
		25: "GuestWriteFailed",
		26: "BadId",
		27: "NotReady",
		28: "NotRequired",
		29: "RunTimeout",
		30: "ReadOneTimeout",
		31: "BadCallId",
	}
	KernelErr_value = map[string]int32{
		"NoError":                        0,
		"LocateError":                    1,
		"UnmarshalFailed":                2,
		"IdDispatch":                     3,
		"NamespaceExhausted":             4,
		"NotFound":                       5,
		"DataTooLarge":                   6,
		"MarshalFailed":                  7,
		"CallerUnavailable":              8,
		"ServiceAlreadyClosedOrExported": 9,
		"ServiceAlreadyRequired":         10,
		"DependencyCycle":                11,
		"NetworkFailed":                  12,
		"NetworkConnectionLost":          13,
		"DataTooSmall":                   14,
		"KernelConnectionFailed":         15,
		"NSRetryFailed":                  16,
		"DecodeError":                    17,
		"ExecError":                      18,
		"KernelDependencyFailure":        19,
		"AbortRequest":                   20,
		"ExitRequested":                  21,
		"EncodeError":                    22,
		"ClosedErr":                      23,
		"GuestReadFailed":                24,
		"GuestWriteFailed":               25,
		"BadId":                          26,
		"NotReady":                       27,
		"NotRequired":                    28,
		"RunTimeout":                     29,
		"ReadOneTimeout":                 30,
		"BadCallId":                      31,
	}
)

func (x KernelErr) Enum() *KernelErr {
	p := new(KernelErr)
	*p = x
	return p
}

func (x KernelErr) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KernelErr) Descriptor() protoreflect.EnumDescriptor {
	return file_syscall_v1_syscall_proto_enumTypes[0].Descriptor()
}

func (KernelErr) Type() protoreflect.EnumType {
	return &file_syscall_v1_syscall_proto_enumTypes[0]
}

func (x KernelErr) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KernelErr.Descriptor instead.
func (KernelErr) EnumDescriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{0}
}

type MethodDirection int32

const (
	MethodDirection_METHOD_DIRECTION_UNSPECIFIED MethodDirection = 0
	MethodDirection_METHOD_DIRECTION_IN          MethodDirection = 1
	MethodDirection_METHOD_DIRECTION_OUT         MethodDirection = 2
	MethodDirection_METHOD_DIRECTION_BOTH        MethodDirection = 3
)

// Enum value maps for MethodDirection.
var (
	MethodDirection_name = map[int32]string{
		0: "METHOD_DIRECTION_UNSPECIFIED",
		1: "METHOD_DIRECTION_IN",
		2: "METHOD_DIRECTION_OUT",
		3: "METHOD_DIRECTION_BOTH",
	}
	MethodDirection_value = map[string]int32{
		"METHOD_DIRECTION_UNSPECIFIED": 0,
		"METHOD_DIRECTION_IN":          1,
		"METHOD_DIRECTION_OUT":         2,
		"METHOD_DIRECTION_BOTH":        3,
	}
)

func (x MethodDirection) Enum() *MethodDirection {
	p := new(MethodDirection)
	*p = x
	return p
}

func (x MethodDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MethodDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_syscall_v1_syscall_proto_enumTypes[1].Descriptor()
}

func (MethodDirection) Type() protoreflect.EnumType {
	return &file_syscall_v1_syscall_proto_enumTypes[1]
}

func (x MethodDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MethodDirection.Descriptor instead.
func (MethodDirection) EnumDescriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{1}
}

type MethodBinding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MethodName string    `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	MethodId   *v1.IdRaw `protobuf:"bytes,2,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
}

func (x *MethodBinding) Reset() {
	*x = MethodBinding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodBinding) ProtoMessage() {}

func (x *MethodBinding) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodBinding.ProtoReflect.Descriptor instead.
func (*MethodBinding) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{0}
}

func (x *MethodBinding) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *MethodBinding) GetMethodId() *v1.IdRaw {
	if x != nil {
		return x.MethodId
	}
	return nil
}

// LocateRequest is a read from the kernel of the service id associated with a package, service pair.
type LocateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackageName string    `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	ServiceName string    `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	CalledBy    *v1.IdRaw `protobuf:"bytes,3,opt,name=called_by,json=calledBy,proto3" json:"called_by,omitempty"`
}

func (x *LocateRequest) Reset() {
	*x = LocateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateRequest) ProtoMessage() {}

func (x *LocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateRequest.ProtoReflect.Descriptor instead.
func (*LocateRequest) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{1}
}

func (x *LocateRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *LocateRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LocateRequest) GetCalledBy() *v1.IdRaw {
	if x != nil {
		return x.CalledBy
	}
	return nil
}

// LocateResponse hands back the service Id of the package_name and service_name supplied in the request.
// A service id can be thought of as a (network hostname,port) pair that defines which
// service's "location".
type LocateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId    *v1.IdRaw        `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ServiceId *v1.IdRaw        `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Binding   []*MethodBinding `protobuf:"bytes,3,rep,name=binding,proto3" json:"binding,omitempty"`
}

func (x *LocateResponse) Reset() {
	*x = LocateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocateResponse) ProtoMessage() {}

func (x *LocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocateResponse.ProtoReflect.Descriptor instead.
func (*LocateResponse) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{2}
}

func (x *LocateResponse) GetHostId() *v1.IdRaw {
	if x != nil {
		return x.HostId
	}
	return nil
}

func (x *LocateResponse) GetServiceId() *v1.IdRaw {
	if x != nil {
		return x.ServiceId
	}
	return nil
}

func (x *LocateResponse) GetBinding() []*MethodBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

// DispatchRequest is a request by a client to invoke a particular method with the parameters provided.
type DispatchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId *v1.IdRaw  `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MethodId  *v1.IdRaw  `protobuf:"bytes,2,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	Param     *anypb.Any `protobuf:"bytes,3,opt,name=param,proto3" json:"param,omitempty"` // inside is another Request object, but we don't know its type
	CallId    *v1.IdRaw  `protobuf:"bytes,4,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	HostId    *v1.IdRaw  `protobuf:"bytes,5,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
}

func (x *DispatchRequest) Reset() {
	*x = DispatchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchRequest) ProtoMessage() {}

func (x *DispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchRequest.ProtoReflect.Descriptor instead.
func (*DispatchRequest) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{3}
}

func (x *DispatchRequest) GetServiceId() *v1.IdRaw {
	if x != nil {
		return x.ServiceId
	}
	return nil
}

func (x *DispatchRequest) GetMethodId() *v1.IdRaw {
	if x != nil {
		return x.MethodId
	}
	return nil
}

func (x *DispatchRequest) GetParam() *anypb.Any {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *DispatchRequest) GetCallId() *v1.IdRaw {
	if x != nil {
		return x.CallId
	}
	return nil
}

func (x *DispatchRequest) GetHostId() *v1.IdRaw {
	if x != nil {
		return x.HostId
	}
	return nil
}

// DispatchResponse sent by the server back to a client.  This what is returned
// as the intermediate value to the caller, because the caller
// cannot block.  This call_id value can be used on the client side
// to map to additional info about the call.
type DispatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CallId *v1.IdRaw `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
}

func (x *DispatchResponse) Reset() {
	*x = DispatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchResponse) ProtoMessage() {}

func (x *DispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchResponse.ProtoReflect.Descriptor instead.
func (*DispatchResponse) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{4}
}

func (x *DispatchResponse) GetCallId() *v1.IdRaw {
	if x != nil {
		return x.CallId
	}
	return nil
}

// ReturnValueRequest is used to return the result of a
// function back to the caller. It is the result information
// of a call to a service/method function.
type ReturnValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId      *v1.IdRaw  `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CallId      *v1.IdRaw  `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Result      *anypb.Any `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	ResultError int32      `protobuf:"varint,4,opt,name=result_error,json=resultError,proto3" json:"result_error,omitempty"`
}

func (x *ReturnValueRequest) Reset() {
	*x = ReturnValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnValueRequest) ProtoMessage() {}

func (x *ReturnValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnValueRequest.ProtoReflect.Descriptor instead.
func (*ReturnValueRequest) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{5}
}

func (x *ReturnValueRequest) GetHostId() *v1.IdRaw {
	if x != nil {
		return x.HostId
	}
	return nil
}

func (x *ReturnValueRequest) GetCallId() *v1.IdRaw {
	if x != nil {
		return x.CallId
	}
	return nil
}

func (x *ReturnValueRequest) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReturnValueRequest) GetResultError() int32 {
	if x != nil {
		return x.ResultError
	}
	return 0
}

// ReturnValueResponse is currently empty.
type ReturnValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnValueResponse) Reset() {
	*x = ReturnValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnValueResponse) ProtoMessage() {}

func (x *ReturnValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnValueResponse.ProtoReflect.Descriptor instead.
func (*ReturnValueResponse) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{6}
}

type BlockUntilCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CanTimeout bool `protobuf:"varint,1,opt,name=can_timeout,json=canTimeout,proto3" json:"can_timeout,omitempty"`
}

func (x *BlockUntilCallRequest) Reset() {
	*x = BlockUntilCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockUntilCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUntilCallRequest) ProtoMessage() {}

func (x *BlockUntilCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUntilCallRequest.ProtoReflect.Descriptor instead.
func (*BlockUntilCallRequest) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{7}
}

func (x *BlockUntilCallRequest) GetCanTimeout() bool {
	if x != nil {
		return x.CanTimeout
	}
	return false
}

type BlockUntilCallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Param    *anypb.Any `protobuf:"bytes,1,opt,name=param,proto3" json:"param,omitempty"`
	Method   *v1.IdRaw  `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Call     *v1.IdRaw  `protobuf:"bytes,3,opt,name=call,proto3" json:"call,omitempty"`
	TimedOut bool       `protobuf:"varint,4,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
}

func (x *BlockUntilCallResponse) Reset() {
	*x = BlockUntilCallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockUntilCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUntilCallResponse) ProtoMessage() {}

func (x *BlockUntilCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUntilCallResponse.ProtoReflect.Descriptor instead.
func (*BlockUntilCallResponse) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{8}
}

func (x *BlockUntilCallResponse) GetParam() *anypb.Any {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *BlockUntilCallResponse) GetMethod() *v1.IdRaw {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *BlockUntilCallResponse) GetCall() *v1.IdRaw {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *BlockUntilCallResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

type BindMethodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId     *v1.IdRaw       `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ServiceId  *v1.IdRaw       `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MethodName string          `protobuf:"bytes,3,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Direction  MethodDirection `protobuf:"varint,4,opt,name=direction,proto3,enum=syscall.v1.MethodDirection" json:"direction,omitempty"`
}

func (x *BindMethodRequest) Reset() {
	*x = BindMethodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMethodRequest) ProtoMessage() {}

func (x *BindMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMethodRequest.ProtoReflect.Descriptor instead.
func (*BindMethodRequest) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{9}
}

func (x *BindMethodRequest) GetHostId() *v1.IdRaw {
	if x != nil {
		return x.HostId
	}
	return nil
}

func (x *BindMethodRequest) GetServiceId() *v1.IdRaw {
	if x != nil {
		return x.ServiceId
	}
	return nil
}

func (x *BindMethodRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *BindMethodRequest) GetDirection() MethodDirection {
	if x != nil {
		return x.Direction
	}
	return MethodDirection_METHOD_DIRECTION_UNSPECIFIED
}

type BindMethodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MethodId *v1.IdRaw `protobuf:"bytes,1,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
}

func (x *BindMethodResponse) Reset() {
	*x = BindMethodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMethodResponse) ProtoMessage() {}

func (x *BindMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMethodResponse.ProtoReflect.Descriptor instead.
func (*BindMethodResponse) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{10}
}

func (x *BindMethodResponse) GetMethodId() *v1.IdRaw {
	if x != nil {
		return x.MethodId
	}
	return nil
}

type FullyQualifiedService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackagePath string `protobuf:"bytes,1,opt,name=package_path,json=packagePath,proto3" json:"package_path,omitempty"`
	Service     string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
}

func (x *FullyQualifiedService) Reset() {
	*x = FullyQualifiedService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullyQualifiedService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullyQualifiedService) ProtoMessage() {}

func (x *FullyQualifiedService) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullyQualifiedService.ProtoReflect.Descriptor instead.
func (*FullyQualifiedService) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{11}
}

func (x *FullyQualifiedService) GetPackagePath() string {
	if x != nil {
		return x.PackagePath
	}
	return ""
}

func (x *FullyQualifiedService) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// ExportRequest informs the kernel that the given
// service id implements the named services on the
// host given.  Note that the services provided must be
// distinct.
type ExportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId *v1.IdRaw                `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Service   []*FullyQualifiedService `protobuf:"bytes,2,rep,name=service,proto3" json:"service,omitempty"`
	HostId    *v1.IdRaw                `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{12}
}

func (x *ExportRequest) GetServiceId() *v1.IdRaw {
	if x != nil {
		return x.ServiceId
	}
	return nil
}

func (x *ExportRequest) GetService() []*FullyQualifiedService {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *ExportRequest) GetHostId() *v1.IdRaw {
	if x != nil {
		return x.HostId
	}
	return nil
}

type ExportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{13}
}

type RequireRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dest   []*FullyQualifiedService `protobuf:"bytes,1,rep,name=dest,proto3" json:"dest,omitempty"`
	Source *v1.IdRaw                `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *RequireRequest) Reset() {
	*x = RequireRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequireRequest) ProtoMessage() {}

func (x *RequireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequireRequest.ProtoReflect.Descriptor instead.
func (*RequireRequest) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{14}
}

func (x *RequireRequest) GetDest() []*FullyQualifiedService {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *RequireRequest) GetSource() *v1.IdRaw {
	if x != nil {
		return x.Source
	}
	return nil
}

type RequireResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequireResponse) Reset() {
	*x = RequireResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequireResponse) ProtoMessage() {}

func (x *RequireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequireResponse.ProtoReflect.Descriptor instead.
func (*RequireResponse) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{15}
}

type LaunchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId *v1.IdRaw `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
}

func (x *LaunchRequest) Reset() {
	*x = LaunchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRequest) ProtoMessage() {}

func (x *LaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRequest.ProtoReflect.Descriptor instead.
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{16}
}

func (x *LaunchRequest) GetServiceId() *v1.IdRaw {
	if x != nil {
		return x.ServiceId
	}
	return nil
}

type LaunchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LaunchResponse) Reset() {
	*x = LaunchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchResponse) ProtoMessage() {}

func (x *LaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchResponse.ProtoReflect.Descriptor instead.
func (*LaunchResponse) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{17}
}

// ExitRequest is how you can request for your wasm program to exit. In some cases, this will not terminate
// the process because there may be other services running in the same process.
type ExitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// valid values here are 0...192 and values>192 or <0 will be set to 192
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ExitRequest) Reset() {
	*x = ExitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitRequest) ProtoMessage() {}

func (x *ExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitRequest.ProtoReflect.Descriptor instead.
func (*ExitRequest) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{18}
}

func (x *ExitRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ExitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ExitResponse) Reset() {
	*x = ExitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitResponse) ProtoMessage() {}

func (x *ExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitResponse.ProtoReflect.Descriptor instead.
func (*ExitResponse) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{19}
}

func (x *ExitResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// Register informs the kernel you are one of the known services
// that can be accessed.  Clients use this so they can participate
// in the dependency graph for startup order.
type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fqs      *FullyQualifiedService `protobuf:"bytes,1,opt,name=fqs,proto3" json:"fqs,omitempty"`
	IsClient bool                   `protobuf:"varint,2,opt,name=is_client,json=isClient,proto3" json:"is_client,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterRequest) GetFqs() *FullyQualifiedService {
	if x != nil {
		return x.Fqs
	}
	return nil
}

func (x *RegisterRequest) GetIsClient() bool {
	if x != nil {
		return x.IsClient
	}
	return false
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                *v1.IdRaw `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExistedPreviously bool      `protobuf:"varint,2,opt,name=existed_previously,json=existedPreviously,proto3" json:"existed_previously,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterResponse) GetId() *v1.IdRaw {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *RegisterResponse) GetExistedPreviously() bool {
	if x != nil {
		return x.ExistedPreviously
	}
	return false
}

type ServiceMethodCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceId *v1.IdRaw `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	MethodId  *v1.IdRaw `protobuf:"bytes,2,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
}

func (x *ServiceMethodCall) Reset() {
	*x = ServiceMethodCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceMethodCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMethodCall) ProtoMessage() {}

func (x *ServiceMethodCall) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMethodCall.ProtoReflect.Descriptor instead.
func (*ServiceMethodCall) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{22}
}

func (x *ServiceMethodCall) GetServiceId() *v1.IdRaw {
	if x != nil {
		return x.ServiceId
	}
	return nil
}

func (x *ServiceMethodCall) GetMethodId() *v1.IdRaw {
	if x != nil {
		return x.MethodId
	}
	return nil
}

type ResolvedCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostId      *v1.IdRaw  `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	CallId      *v1.IdRaw  `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Result      *anypb.Any `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	ResultError int32      `protobuf:"varint,4,opt,name=result_error,json=resultError,proto3" json:"result_error,omitempty"`
}

func (x *ResolvedCall) Reset() {
	*x = ResolvedCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResolvedCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvedCall) ProtoMessage() {}

func (x *ResolvedCall) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvedCall.ProtoReflect.Descriptor instead.
func (*ResolvedCall) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{23}
}

func (x *ResolvedCall) GetHostId() *v1.IdRaw {
	if x != nil {
		return x.HostId
	}
	return nil
}

func (x *ResolvedCall) GetCallId() *v1.IdRaw {
	if x != nil {
		return x.CallId
	}
	return nil
}

func (x *ResolvedCall) GetResult() *anypb.Any {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResolvedCall) GetResultError() int32 {
	if x != nil {
		return x.ResultError
	}
	return 0
}

// ReadOneRequest gives a set of service/method pairs
// that should be considered for a read.  The ReadOne
// operation returns a single service/method pair that
// has received a call. If the timeout expires, only
// the timeout bool is returned. If the timeout value
// is 0, then an instanteous sample is returned.  If
// the timeout value is negative, it means wait forever.
// In addition to potential calls on the service who
// requests this read, it is also possible that the
// return value represents a completed call from a previous
// point in the execution of the calling program.
type ReadOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Call            []*ServiceMethodCall `protobuf:"bytes,1,rep,name=call,proto3" json:"call,omitempty"`
	TimeoutInMillis int32                `protobuf:"varint,2,opt,name=timeout_in_millis,json=timeoutInMillis,proto3" json:"timeout_in_millis,omitempty"`
	HostId          *v1.IdRaw            `protobuf:"bytes,3,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
}

func (x *ReadOneRequest) Reset() {
	*x = ReadOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOneRequest) ProtoMessage() {}

func (x *ReadOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOneRequest.ProtoReflect.Descriptor instead.
func (*ReadOneRequest) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{24}
}

func (x *ReadOneRequest) GetCall() []*ServiceMethodCall {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *ReadOneRequest) GetTimeoutInMillis() int32 {
	if x != nil {
		return x.TimeoutInMillis
	}
	return 0
}

func (x *ReadOneRequest) GetHostId() *v1.IdRaw {
	if x != nil {
		return x.HostId
	}
	return nil
}

// ReadOneResponse is returned when the control
// is turned over to parigot for a period of time via
// a call to ReadOne.
// ReadOneResponse returns timeout = true if a timeout
// has occurred. If timeout is true, all the other fields
// should be ignored. There are two types of results and
// these are mutually exclusive.
//
// If resolved is not nil, then this a notification that a
// call made by this program have completed.  The
// resolved field holds information about the completed call,
// and that data needs to be matched with the appropriate call ids
// and the promises resolved.
//
// If resolved is nil, then the call is a call
// on a service and method exposed by this server.
// In that case the pair indicates the method and service
// being invoked, and the param and call id should be
// to create a matching ReturnValueRequest.
//
// Note that if the method denoted by the pair does not
// take input, the value of param should be ignored and
// it may be nil.
type ReadOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeout  bool               `protobuf:"varint,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Call     *ServiceMethodCall `protobuf:"bytes,2,opt,name=call,proto3" json:"call,omitempty"`
	CallId   *v1.IdRaw          `protobuf:"bytes,3,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Param    *anypb.Any         `protobuf:"bytes,4,opt,name=param,proto3" json:"param,omitempty"`
	Resolved *ResolvedCall      `protobuf:"bytes,5,opt,name=resolved,proto3" json:"resolved,omitempty"`
}

func (x *ReadOneResponse) Reset() {
	*x = ReadOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syscall_v1_syscall_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOneResponse) ProtoMessage() {}

func (x *ReadOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_syscall_v1_syscall_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOneResponse.ProtoReflect.Descriptor instead.
func (*ReadOneResponse) Descriptor() ([]byte, []int) {
	return file_syscall_v1_syscall_proto_rawDescGZIP(), []int{25}
}

func (x *ReadOneResponse) GetTimeout() bool {
	if x != nil {
		return x.Timeout
	}
	return false
}

func (x *ReadOneResponse) GetCall() *ServiceMethodCall {
	if x != nil {
		return x.Call
	}
	return nil
}

func (x *ReadOneResponse) GetCallId() *v1.IdRaw {
	if x != nil {
		return x.CallId
	}
	return nil
}

func (x *ReadOneResponse) GetParam() *anypb.Any {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *ReadOneResponse) GetResolved() *ResolvedCall {
	if x != nil {
		return x.Resolved
	}
	return nil
}

var File_syscall_v1_syscall_proto protoreflect.FileDescriptor

var file_syscall_v1_syscall_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x79, 0x73,
	0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x79, 0x73, 0x63,
	0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52,
	0x61, 0x77, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x22, 0x8a, 0x01, 0x0a,
	0x0d, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21,
	0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x62,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52,
	0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x64, 0x42, 0x79, 0x22, 0xad, 0x01, 0x0a, 0x0e, 0x4c, 0x6f,
	0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07,
	0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x35, 0x0a,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x52, 0x07, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x8b, 0x02, 0x0a, 0x0f, 0x44, 0x69,
	0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75,
	0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x06,
	0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52,
	0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x63,
	0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x64, 0x52, 0x61, 0x77, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0xc7, 0x01, 0x0a,
	0x12, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x06, 0x68, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70,
	0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x06, 0x63,
	0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x5f, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x38, 0x0a,
	0x15, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x6e, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x61, 0x6e,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0xbd, 0x01, 0x0a, 0x16, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x55, 0x6e, 0x74, 0x69, 0x6c, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x2e,
	0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x2a,
	0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x64, 0x52, 0x61, 0x77, 0x52, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x64, 0x5f, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x74,
	0x69, 0x6d, 0x65, 0x64, 0x4f, 0x75, 0x74, 0x22, 0xd7, 0x01, 0x0a, 0x11, 0x42, 0x69, 0x6e, 0x64,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a,
	0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x35,
	0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x73, 0x79, 0x73, 0x63,
	0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x49, 0x0a, 0x12, 0x42, 0x69, 0x6e, 0x64, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52,
	0x61, 0x77, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x22, 0x54, 0x0a, 0x15,
	0x46, 0x75, 0x6c, 0x6c, 0x79, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x64, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0xb4, 0x01, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77,
	0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73,
	0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x79, 0x51,
	0x75, 0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61,
	0x77, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x22, 0x10, 0x0a, 0x0e, 0x45, 0x78, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x77, 0x0a, 0x0e, 0x52,
	0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a,
	0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x79,
	0x73, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x79, 0x51, 0x75,
	0x61, 0x6c, 0x69, 0x66, 0x69, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x04,
	0x64, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70,
	0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x46, 0x0a, 0x0d, 0x4c, 0x61, 0x75, 0x6e, 0x63,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x64, 0x52, 0x61, 0x77, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22,
	0x10, 0x0a, 0x0e, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x21, 0x0a, 0x0b, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x45, 0x78, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x63, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x33, 0x0a, 0x03, 0x66,
	0x71, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x79, 0x73, 0x63, 0x61,
	0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x75, 0x6c, 0x6c, 0x79, 0x51, 0x75, 0x61, 0x6c, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x03, 0x66, 0x71, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x69, 0x0a,
	0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x65, 0x78, 0x69,
	0x73, 0x74, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x6c, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x65, 0x78, 0x69, 0x73, 0x74, 0x65, 0x64, 0x50, 0x72,
	0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x6c, 0x79, 0x22, 0x7f, 0x0a, 0x11, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x35, 0x0a,
	0x0a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x49, 0x64, 0x22, 0xc1, 0x01, 0x0a, 0x0c, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x2f, 0x0a, 0x07, 0x68, 0x6f,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64,
	0x52, 0x61, 0x77, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x07, 0x63,
	0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49,
	0x64, 0x52, 0x61, 0x77, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0b, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xa0, 0x01,
	0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x31, 0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x04, 0x63,
	0x61, 0x6c, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x69,
	0x6e, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f,
	0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x49, 0x6e, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x73, 0x12,
	0x2f, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x22, 0xf1, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x31,
	0x0a, 0x04, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73,
	0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x04, 0x63, 0x61, 0x6c,
	0x6c, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x61, 0x6c, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x75, 0x70, 0x70, 0x6f, 0x72,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x52, 0x61, 0x77, 0x52, 0x06, 0x63, 0x61, 0x6c, 0x6c,
	0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x34,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x73, 0x6f, 0x6c, 0x76, 0x65, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x6c, 0x76, 0x65, 0x64, 0x2a, 0x85, 0x05, 0x0a, 0x09, 0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x45,
	0x72, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x01,
	0x12, 0x13, 0x0a, 0x0f, 0x55, 0x6e, 0x6d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x46, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x64, 0x44, 0x69, 0x73, 0x70, 0x61,
	0x74, 0x63, 0x68, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x45, 0x78, 0x68, 0x61, 0x75, 0x73, 0x74, 0x65, 0x64, 0x10, 0x04, 0x12, 0x0c, 0x0a,
	0x08, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0x05, 0x12, 0x10, 0x0a, 0x0c, 0x44,
	0x61, 0x74, 0x61, 0x54, 0x6f, 0x6f, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x10, 0x06, 0x12, 0x11, 0x0a,
	0x0d, 0x4d, 0x61, 0x72, 0x73, 0x68, 0x61, 0x6c, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x07,
	0x12, 0x15, 0x0a, 0x11, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x55, 0x6e, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x10, 0x08, 0x12, 0x22, 0x0a, 0x1e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x4f,
	0x72, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x10, 0x09, 0x12, 0x1a, 0x0a, 0x16, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x10, 0x0a, 0x12, 0x13, 0x0a, 0x0f, 0x44, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x10, 0x0b, 0x12, 0x11, 0x0a, 0x0d,
	0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x0c, 0x12,
	0x19, 0x0a, 0x15, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x73, 0x74, 0x10, 0x0d, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x6f, 0x6f, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x10, 0x0e, 0x12, 0x1a, 0x0a, 0x16,
	0x4b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x0f, 0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x53, 0x52, 0x65,
	0x74, 0x72, 0x79, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x10, 0x12, 0x0f, 0x0a, 0x0b, 0x44,
	0x65, 0x63, 0x6f, 0x64, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x11, 0x12, 0x0d, 0x0a, 0x09,
	0x45, 0x78, 0x65, 0x63, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x12, 0x12, 0x1b, 0x0a, 0x17, 0x4b,
	0x65, 0x72, 0x6e, 0x65, 0x6c, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x46,
	0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x10, 0x13, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x62, 0x6f, 0x72,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x14, 0x12, 0x11, 0x0a, 0x0d, 0x45, 0x78,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x10, 0x15, 0x12, 0x0f, 0x0a,
	0x0b, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x16, 0x12, 0x0d,
	0x0a, 0x09, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x45, 0x72, 0x72, 0x10, 0x17, 0x12, 0x13, 0x0a,
	0x0f, 0x47, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x61, 0x64, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x10, 0x18, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x75, 0x65, 0x73, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x19, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x61, 0x64, 0x49,
	0x64, 0x10, 0x1a, 0x12, 0x0c, 0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x61, 0x64, 0x79, 0x10,
	0x1b, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x6f, 0x74, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64,
	0x10, 0x1c, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x10, 0x1d, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x4f, 0x6e, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x6f, 0x75, 0x74, 0x10, 0x1e, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x61, 0x64, 0x43, 0x61, 0x6c,
	0x6c, 0x49, 0x64, 0x10, 0x1f, 0x1a, 0x05, 0xd8, 0x9e, 0x89, 0x02, 0x01, 0x2a, 0x81, 0x01, 0x0a,
	0x0f, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x20, 0x0a, 0x1c, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x44, 0x49, 0x52,
	0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x4d,
	0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x4f, 0x55, 0x54, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f,
	0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x42, 0x4f, 0x54, 0x48, 0x10, 0x03,
	0x42, 0x16, 0x5a, 0x14, 0x67, 0x2f, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x2f, 0x76, 0x31,
	0x3b, 0x73, 0x79, 0x73, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_syscall_v1_syscall_proto_rawDescOnce sync.Once
	file_syscall_v1_syscall_proto_rawDescData = file_syscall_v1_syscall_proto_rawDesc
)

func file_syscall_v1_syscall_proto_rawDescGZIP() []byte {
	file_syscall_v1_syscall_proto_rawDescOnce.Do(func() {
		file_syscall_v1_syscall_proto_rawDescData = protoimpl.X.CompressGZIP(file_syscall_v1_syscall_proto_rawDescData)
	})
	return file_syscall_v1_syscall_proto_rawDescData
}

var file_syscall_v1_syscall_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_syscall_v1_syscall_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_syscall_v1_syscall_proto_goTypes = []interface{}{
	(KernelErr)(0),                 // 0: syscall.v1.KernelErr
	(MethodDirection)(0),           // 1: syscall.v1.MethodDirection
	(*MethodBinding)(nil),          // 2: syscall.v1.MethodBinding
	(*LocateRequest)(nil),          // 3: syscall.v1.LocateRequest
	(*LocateResponse)(nil),         // 4: syscall.v1.LocateResponse
	(*DispatchRequest)(nil),        // 5: syscall.v1.DispatchRequest
	(*DispatchResponse)(nil),       // 6: syscall.v1.DispatchResponse
	(*ReturnValueRequest)(nil),     // 7: syscall.v1.ReturnValueRequest
	(*ReturnValueResponse)(nil),    // 8: syscall.v1.ReturnValueResponse
	(*BlockUntilCallRequest)(nil),  // 9: syscall.v1.BlockUntilCallRequest
	(*BlockUntilCallResponse)(nil), // 10: syscall.v1.BlockUntilCallResponse
	(*BindMethodRequest)(nil),      // 11: syscall.v1.BindMethodRequest
	(*BindMethodResponse)(nil),     // 12: syscall.v1.BindMethodResponse
	(*FullyQualifiedService)(nil),  // 13: syscall.v1.FullyQualifiedService
	(*ExportRequest)(nil),          // 14: syscall.v1.ExportRequest
	(*ExportResponse)(nil),         // 15: syscall.v1.ExportResponse
	(*RequireRequest)(nil),         // 16: syscall.v1.RequireRequest
	(*RequireResponse)(nil),        // 17: syscall.v1.RequireResponse
	(*LaunchRequest)(nil),          // 18: syscall.v1.LaunchRequest
	(*LaunchResponse)(nil),         // 19: syscall.v1.LaunchResponse
	(*ExitRequest)(nil),            // 20: syscall.v1.ExitRequest
	(*ExitResponse)(nil),           // 21: syscall.v1.ExitResponse
	(*RegisterRequest)(nil),        // 22: syscall.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 23: syscall.v1.RegisterResponse
	(*ServiceMethodCall)(nil),      // 24: syscall.v1.ServiceMethodCall
	(*ResolvedCall)(nil),           // 25: syscall.v1.ResolvedCall
	(*ReadOneRequest)(nil),         // 26: syscall.v1.ReadOneRequest
	(*ReadOneResponse)(nil),        // 27: syscall.v1.ReadOneResponse
	(*v1.IdRaw)(nil),               // 28: protosupport.v1.IdRaw
	(*anypb.Any)(nil),              // 29: google.protobuf.Any
}
var file_syscall_v1_syscall_proto_depIdxs = []int32{
	28, // 0: syscall.v1.MethodBinding.method_id:type_name -> protosupport.v1.IdRaw
	28, // 1: syscall.v1.LocateRequest.called_by:type_name -> protosupport.v1.IdRaw
	28, // 2: syscall.v1.LocateResponse.host_id:type_name -> protosupport.v1.IdRaw
	28, // 3: syscall.v1.LocateResponse.service_id:type_name -> protosupport.v1.IdRaw
	2,  // 4: syscall.v1.LocateResponse.binding:type_name -> syscall.v1.MethodBinding
	28, // 5: syscall.v1.DispatchRequest.service_id:type_name -> protosupport.v1.IdRaw
	28, // 6: syscall.v1.DispatchRequest.method_id:type_name -> protosupport.v1.IdRaw
	29, // 7: syscall.v1.DispatchRequest.param:type_name -> google.protobuf.Any
	28, // 8: syscall.v1.DispatchRequest.call_id:type_name -> protosupport.v1.IdRaw
	28, // 9: syscall.v1.DispatchRequest.host_id:type_name -> protosupport.v1.IdRaw
	28, // 10: syscall.v1.DispatchResponse.call_id:type_name -> protosupport.v1.IdRaw
	28, // 11: syscall.v1.ReturnValueRequest.host_id:type_name -> protosupport.v1.IdRaw
	28, // 12: syscall.v1.ReturnValueRequest.call_id:type_name -> protosupport.v1.IdRaw
	29, // 13: syscall.v1.ReturnValueRequest.result:type_name -> google.protobuf.Any
	29, // 14: syscall.v1.BlockUntilCallResponse.param:type_name -> google.protobuf.Any
	28, // 15: syscall.v1.BlockUntilCallResponse.method:type_name -> protosupport.v1.IdRaw
	28, // 16: syscall.v1.BlockUntilCallResponse.call:type_name -> protosupport.v1.IdRaw
	28, // 17: syscall.v1.BindMethodRequest.host_id:type_name -> protosupport.v1.IdRaw
	28, // 18: syscall.v1.BindMethodRequest.service_id:type_name -> protosupport.v1.IdRaw
	1,  // 19: syscall.v1.BindMethodRequest.direction:type_name -> syscall.v1.MethodDirection
	28, // 20: syscall.v1.BindMethodResponse.method_id:type_name -> protosupport.v1.IdRaw
	28, // 21: syscall.v1.ExportRequest.service_id:type_name -> protosupport.v1.IdRaw
	13, // 22: syscall.v1.ExportRequest.service:type_name -> syscall.v1.FullyQualifiedService
	28, // 23: syscall.v1.ExportRequest.host_id:type_name -> protosupport.v1.IdRaw
	13, // 24: syscall.v1.RequireRequest.dest:type_name -> syscall.v1.FullyQualifiedService
	28, // 25: syscall.v1.RequireRequest.source:type_name -> protosupport.v1.IdRaw
	28, // 26: syscall.v1.LaunchRequest.service_id:type_name -> protosupport.v1.IdRaw
	13, // 27: syscall.v1.RegisterRequest.fqs:type_name -> syscall.v1.FullyQualifiedService
	28, // 28: syscall.v1.RegisterResponse.id:type_name -> protosupport.v1.IdRaw
	28, // 29: syscall.v1.ServiceMethodCall.service_id:type_name -> protosupport.v1.IdRaw
	28, // 30: syscall.v1.ServiceMethodCall.method_id:type_name -> protosupport.v1.IdRaw
	28, // 31: syscall.v1.ResolvedCall.host_id:type_name -> protosupport.v1.IdRaw
	28, // 32: syscall.v1.ResolvedCall.call_id:type_name -> protosupport.v1.IdRaw
	29, // 33: syscall.v1.ResolvedCall.result:type_name -> google.protobuf.Any
	24, // 34: syscall.v1.ReadOneRequest.call:type_name -> syscall.v1.ServiceMethodCall
	28, // 35: syscall.v1.ReadOneRequest.host_id:type_name -> protosupport.v1.IdRaw
	24, // 36: syscall.v1.ReadOneResponse.call:type_name -> syscall.v1.ServiceMethodCall
	28, // 37: syscall.v1.ReadOneResponse.call_id:type_name -> protosupport.v1.IdRaw
	29, // 38: syscall.v1.ReadOneResponse.param:type_name -> google.protobuf.Any
	25, // 39: syscall.v1.ReadOneResponse.resolved:type_name -> syscall.v1.ResolvedCall
	40, // [40:40] is the sub-list for method output_type
	40, // [40:40] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_syscall_v1_syscall_proto_init() }
func file_syscall_v1_syscall_proto_init() {
	if File_syscall_v1_syscall_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_syscall_v1_syscall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodBinding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LocateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DispatchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DispatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockUntilCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockUntilCallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindMethodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindMethodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FullyQualifiedService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequireRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequireResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LaunchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LaunchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceMethodCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResolvedCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syscall_v1_syscall_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_syscall_v1_syscall_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_syscall_v1_syscall_proto_goTypes,
		DependencyIndexes: file_syscall_v1_syscall_proto_depIdxs,
		EnumInfos:         file_syscall_v1_syscall_proto_enumTypes,
		MessageInfos:      file_syscall_v1_syscall_proto_msgTypes,
	}.Build()
	File_syscall_v1_syscall_proto = out.File
	file_syscall_v1_syscall_proto_rawDesc = nil
	file_syscall_v1_syscall_proto_goTypes = nil
	file_syscall_v1_syscall_proto_depIdxs = nil
}
