[process]
foo = "build/foo.p.wasm"
bar = "build/bar.p.wasm"
log = "api/atlanta/build/log.p.wasm"

[test]
methodcall = "build/methodcall_test.p.wasm"
multimethodcall = "build/multimethodcall_test.p.wasm"
