## Note that because this file is expected to be consumed in the parigot dev container
## that builds with the hello world Makefile.  The files here have paths that 
## are relative to this file, but the path to ParigotLibPath expects that
## this program is inside the parigot repo itself.

## dev configuration in general
[config.dev]
## Load parigot code from shared object
ParigotLibPath="syscall.so" #uses SearchDir
ParigotLibSymbol="ParigotInitialize"
Timezone = "US/Eastern"
[config.dev.Timeout]
Startup = 100 # millis
Complete = 20 # millis


# greeting service
[config.dev.microservice.greet]
WasmPath="build/greeting.p.wasm"
Arg=[]
Env=[]

# helloworld, it has no services that it implements, it just consumes greet and
# runs to the end of main.
[config.dev.microservice.helloworld]
WasmPath="build/hello.p.wasm"
Arg=[]
Env=[]
# this is the crucial line for parigot. "this is just a client and should run to completion".
Main=true

