# there is no main "program" these two services just exist in the void...

## Note that because this file is expected to be consumed in a dev container
## so the files have absolute paths that are correct for the container.

## dev configuration in general
[config.dev]
## Load parigot code from shared object
ParigotLibPath="/workspaces/parigot/build/syscall.so"
ParigotLibSymbol="ParigotInitialize"
Timezone = "US/Eastern"
[config.dev.Timeout]
Startup = 100 # millis
Complete = 20 # millis

# the simple service
[config.dev.microservice.simple]
WasmPath="/workspaces/parigot/example/httpsimple/build/simple.p.wasm"
Arg=[]
Env=[]

# frontdoor service
[config.dev.microservice.frontdoor]
WasmPath="/workspaces/parigot/example/httpsimple/build/frontdoor.p.wasm"
Arg=[]
Env=[]

