package main

import (
	"fmt"
	"google.golang.org/protobuf/compiler/protogen"
	"log"
	"strings"
)

const (
	wasmServiceName = "WasmServiceName"
	wasmFuncName    = "WasmFuncName"
)

var parigotPrefixes = []string{
	"//parigot:",
	"// parigot:",
}

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			generateFile(gen, f)
		}
		return nil
	})
}

// generateFile generates a suitable interface for use with parigot
func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + ".p.toml"

	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P(fmt.Sprintf("## Code generated by protoc-gen-parigot from %s ...DO NOT EDIT.",
		file.Desc.Path()))
	g.P()

	for _, s := range file.Services {
		wasmName := s.GoName
		optName := wasmNameFromComment(s.Comments.Leading.String())
		if optName != "" {
			wasmName = optName
		}
		g.P("[parigot." + s.GoName + "]")
		g.P("  name=\"", s.GoName, "\"")
		g.P("  protoFile=\"", file.Desc.Path()+"\"")
		g.P("  wasmServiceName=\"", wasmName, "\"")
		g.P("  goPackage=\"", file.GoPackageName+"\"")

		g.P()
	}
	g.P()

	return g
}
func wasmNameFromComment(s string) string {
	settings := parigotCommentSettings(parigotCommentLine(s))
	if settings == nil {
		return ""
	}
	wasmName, ok := settings[wasmServiceName]
	if !ok {
		return ""
	}
	return wasmName
}
func parigotCommentLine(allLines string) string {
	lines := strings.Split(allLines, "\n") // xxx break on windows?
	if len(lines) == 0 {
		return ""
	}
	line := ""
	for l := len(lines) - 1; l >= 0; l-- {
		if lines[l] != "" {
			line = lines[l]
			break
		}
	}
	return line
}

func parigotCommentSettings(line string) map[string]string {
	if line == "" {
		return nil
	}
	found := ""
	for _, p := range parigotPrefixes {
		if strings.HasPrefix(line, p) {
			found = strings.TrimPrefix(line, p)
			break
		}
	}
	if found == "" {
		return nil
	}
	parts := strings.Split(found, ",")
	if len(parts) == 0 {
		panic("cant parse comment line: " + line)
	}
	settings := make(map[string]string)
	for _, setting := range parts {
		parts := strings.Split(setting, "=")
		if len(parts) != 2 {
			log.Printf("can't parse parigot comment setting on line:" + line)
			continue
		}
		key := strings.TrimSpace(parts[0])
		val := strings.TrimSpace(parts[1])
		settings[key] = val
	}
	return settings
}
