name: Tests and Build
'on':
  push:
    branches:
      - alternate
    tags:
      - v*
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: build
        run: make test
      - name: Build Docker image
        run: docker build -t my-test-image -f .devcontainer/Dockerfile
      - name: Run tests using Docker image
        run: docker run --rm my-test-image make test

# runs:
#   using: 'docker'
#   image: Dockerfile'

