name: Go

on:
  push:
    
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Plugin Queue Test
      run: go test -v github.com/iansmith/parigot/api/plugin/queue

    - name: Plugin File Test
      run: go test -v github.com/iansmith/parigot/api/plugin/file

    - name: Go Future Test
      run: go test -v github.com/iansmith/parigot/lib/go/future

    - name: Plugin Syscall Test
      run: go test -v github.com/iansmith/parigot/api/plugin/syscall

    - name: Syscall Wheller
      run: go test -v github.com/iansmith/parigot/api/plugin/syscall/wheeler
