name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - name: Install dependencies
        run: go get -u -d ./...
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
